# Release process
#
# Bump version in Cargo.toml, deployment.yaml, and create a corresponding git tag for it
# Once pushed, CI makes a docker image for the same version

pre-release-replacements = [
  {file="deployment", search=ghcr.io/kube-rs/version-rs:.*", replace=ghcr.io/kube-rs/version-rs:{{version}}"},
]
pre-release-commit-message = "release {{version}}"
push = false
tag = true
tag-name = "{{version}}"
sign-tag = true
sign-commit = true
enable-all-features = true

# Ref: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md
